name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install npm modules
        run: npm install
      - name: Bundle documentation theme
        run: gulp bundle
      - name: Upload ui bundle
        uses: actions/upload-artifact@v2
        with:
          name: bonita-documentation-ui-bundle
          path: build/ui-bundle.zip
          retention-days: 7
